server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/ugaoxin_db?tinyInt1isBit=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  type-aliases-package: com.ugaoxin.springbootmybatisplus.pojo
mybatis-plus:

  mapper-locations: classpath*:com/ugaoxin/springbootmybatisplus/mapper/*/*Mapper.xml